language: ruby
rvm:
  - 2.1.5
cache: bundler
script:
  - echo "Building Development Site"
  - bundle exec "jekyll build --profile"
  - echo "Testing Site"
  - bundle exec htmlproofer ./_site --disable-external --check-html --check-favicon
  - echo "Building Production Site"
  - bundle exec "JEKYLL_ENV=production jekyll build --profile"
  - echo "Testing Site"
  - bundle exec htmlproofer ./_site --disable-external --check-html --check-favicon
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
