language: ruby
rvm:
  - 2.1
script:
  - bundle exec "JEKYLL_ENV=production jekyll build"
  - bundle exec htmlproof ./_site --disable-external --check-html --check-favicon
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer